[package]
edition = "2021"
name = "node-yara-x"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Enable napi4 and async features
napi = { version = "3.12.0", default-features = false, features = ["napi4", "async"] }
napi-derive = "3.6.2"
yara-x = { git = "https://github.com/cawalch/yara-x", branch = "wasmi-runtime", default-features = false, features = [
  "console-module", "pe-module", "elf-module", "macho-module", "math-module",
  "hash-module", "string-module", "time-module", "dotnet-module",
  "constant-folding", "exact-atoms", "fast-regexp", "wasmi-runtime",
] }

[build-dependencies]
napi-build = "2.4.0"

[profile.release]
lto = true
strip = "symbols"
codegen-units = 1
