name: Publish
'on':
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0 or 1.0.0-beta.1)'
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # TODO: Add steps to build, test, and publish
